// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAp4BRH8ZQ7R91rQfTyyPzbLeL8EMLsI',
    appId: '1:674980117376:android:af766acb9ab56f4d9b1f65',
    messagingSenderId: '674980117376',
    projectId: 'fifaworldcup2026-23d01',
    storageBucket: 'fifaworldcup2026-23d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2r6FgJbL2GzMjrsMlu44vHIuVpAPLR1U',
    appId: '1:674980117376:ios:49f737b413f19bb89b1f65',
    messagingSenderId: '674980117376',
    projectId: 'fifaworldcup2026-23d01',
    storageBucket: 'fifaworldcup2026-23d01.firebasestorage.app',
    iosClientId: '674980117376-1uh73usqnf3rji1de02mo4m8ndaohg7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
